### ISSUE TITLE
Water doesn't flow to empty blocks

### ISSUE THREAD

**Issue by Diakon5** [infernalstudios/Ocean-Worlds#1]
I checked this on 1.19.2 and 1.20.1. The naturally generated water doesn't flow into empty spaces at all. Neither down or to the sides, it's a static block with properties of water. Scooping up a bucket only works from "full" blocks, and placed down water behaves as normal

**Comment by SwanX1** [comment]
This is intended, so that the "waves" generated don't flow. The generated water uses a mimicked water, which does not flow.
Without it, the waves would not exist, as well as there would be so many block updates, you could say your last words to your computer, because it would fly up into the sky because of the fans being overloaded, because your CPU would not even have the chance to think about cooling itself down, because it would be too busy thinking about where the water should flow.
Hope this answers your question! :)
